// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: nexus/v1/allocation.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Allocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	NodeId        string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	BackupNodeId  string                 `protobuf:"bytes,6,opt,name=backup_node_id,json=backupNodeId,proto3" json:"backup_node_id,omitempty"`
	IsBackup      bool                   `protobuf:"varint,7,opt,name=is_backup,json=isBackup,proto3" json:"is_backup,omitempty"`
	Ttl           int64                  `protobuf:"varint,8,opt,name=ttl,proto3" json:"ttl,omitempty"`
	Epoch         uint64                 `protobuf:"varint,9,opt,name=epoch,proto3" json:"epoch,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	LastRenewed   *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=last_renewed,json=lastRenewed,proto3" json:"last_renewed,omitempty"`
	AllocType     string                 `protobuf:"bytes,12,opt,name=alloc_type,json=allocType,proto3" json:"alloc_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Allocation) Reset() {
	*x = Allocation{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Allocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Allocation) ProtoMessage() {}

func (x *Allocation) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Allocation.ProtoReflect.Descriptor instead.
func (*Allocation) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{0}
}

func (x *Allocation) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *Allocation) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *Allocation) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *Allocation) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *Allocation) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *Allocation) GetBackupNodeId() string {
	if x != nil {
		return x.BackupNodeId
	}
	return ""
}

func (x *Allocation) GetIsBackup() bool {
	if x != nil {
		return x.IsBackup
	}
	return false
}

func (x *Allocation) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *Allocation) GetEpoch() uint64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *Allocation) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *Allocation) GetLastRenewed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastRenewed
	}
	return nil
}

func (x *Allocation) GetAllocType() string {
	if x != nil {
		return x.AllocType
	}
	return ""
}

type AllocateRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PoolId       string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SubscriberId string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// Optional: specify IP or let the system allocate from the pool.
	Ip string `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	// Optional: primary node that owns this allocation.
	NodeId string `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// Optional: TTL in seconds (0 = permanent).
	Ttl int64 `protobuf:"varint,5,opt,name=ttl,proto3" json:"ttl,omitempty"`
	// Optional: "session", "sticky", "permanent".
	AllocType     string `protobuf:"bytes,6,opt,name=alloc_type,json=allocType,proto3" json:"alloc_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateRequest) Reset() {
	*x = AllocateRequest{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateRequest) ProtoMessage() {}

func (x *AllocateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateRequest.ProtoReflect.Descriptor instead.
func (*AllocateRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{1}
}

func (x *AllocateRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *AllocateRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *AllocateRequest) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocateRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *AllocateRequest) GetTtl() int64 {
	if x != nil {
		return x.Ttl
	}
	return 0
}

func (x *AllocateRequest) GetAllocType() string {
	if x != nil {
		return x.AllocType
	}
	return ""
}

type AllocateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocation    *Allocation            `protobuf:"bytes,1,opt,name=allocation,proto3" json:"allocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocateResponse) Reset() {
	*x = AllocateResponse{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocateResponse) ProtoMessage() {}

func (x *AllocateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocateResponse.ProtoReflect.Descriptor instead.
func (*AllocateResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{2}
}

func (x *AllocateResponse) GetAllocation() *Allocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

type ReleaseRequest struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	// Optional: pool ID. If empty, looked up from subscriber's allocation.
	PoolId        string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseRequest) Reset() {
	*x = ReleaseRequest{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseRequest) ProtoMessage() {}

func (x *ReleaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseRequest.ProtoReflect.Descriptor instead.
func (*ReleaseRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{3}
}

func (x *ReleaseRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *ReleaseRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type ReleaseResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseResponse) Reset() {
	*x = ReleaseResponse{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseResponse) ProtoMessage() {}

func (x *ReleaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseResponse.ProtoReflect.Descriptor instead.
func (*ReleaseResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{4}
}

type GetAllocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SubscriberId  string                 `protobuf:"bytes,1,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationRequest) Reset() {
	*x = GetAllocationRequest{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationRequest) ProtoMessage() {}

func (x *GetAllocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationRequest.ProtoReflect.Descriptor instead.
func (*GetAllocationRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{5}
}

func (x *GetAllocationRequest) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

type GetAllocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocation    *Allocation            `protobuf:"bytes,1,opt,name=allocation,proto3" json:"allocation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllocationResponse) Reset() {
	*x = GetAllocationResponse{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllocationResponse) ProtoMessage() {}

func (x *GetAllocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllocationResponse.ProtoReflect.Descriptor instead.
func (*GetAllocationResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{6}
}

func (x *GetAllocationResponse) GetAllocation() *Allocation {
	if x != nil {
		return x.Allocation
	}
	return nil
}

type ListAllocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsRequest) Reset() {
	*x = ListAllocationsRequest{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsRequest) ProtoMessage() {}

func (x *ListAllocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsRequest.ProtoReflect.Descriptor instead.
func (*ListAllocationsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{7}
}

func (x *ListAllocationsRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type ListAllocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Allocations   []*Allocation          `protobuf:"bytes,1,rep,name=allocations,proto3" json:"allocations,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAllocationsResponse) Reset() {
	*x = ListAllocationsResponse{}
	mi := &file_nexus_v1_allocation_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAllocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAllocationsResponse) ProtoMessage() {}

func (x *ListAllocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_allocation_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAllocationsResponse.ProtoReflect.Descriptor instead.
func (*ListAllocationsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_allocation_proto_rawDescGZIP(), []int{8}
}

func (x *ListAllocationsResponse) GetAllocations() []*Allocation {
	if x != nil {
		return x.Allocations
	}
	return nil
}

func (x *ListAllocationsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_nexus_v1_allocation_proto protoreflect.FileDescriptor

const file_nexus_v1_allocation_proto_rawDesc = "" +
	"\n" +
	"\x19nexus/v1/allocation.proto\x12\bnexus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xb1\x03\n" +
	"\n" +
	"Allocation\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x128\n" +
	"\ttimestamp\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12$\n" +
	"\x0ebackup_node_id\x18\x06 \x01(\tR\fbackupNodeId\x12\x1b\n" +
	"\tis_backup\x18\a \x01(\bR\bisBackup\x12\x10\n" +
	"\x03ttl\x18\b \x01(\x03R\x03ttl\x12\x14\n" +
	"\x05epoch\x18\t \x01(\x04R\x05epoch\x129\n" +
	"\n" +
	"expires_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12=\n" +
	"\flast_renewed\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\vlastRenewed\x12\x1d\n" +
	"\n" +
	"alloc_type\x18\f \x01(\tR\tallocType\"\xa9\x01\n" +
	"\x0fAllocateRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03ttl\x18\x05 \x01(\x03R\x03ttl\x12\x1d\n" +
	"\n" +
	"alloc_type\x18\x06 \x01(\tR\tallocType\"H\n" +
	"\x10AllocateResponse\x124\n" +
	"\n" +
	"allocation\x18\x01 \x01(\v2\x14.nexus.v1.AllocationR\n" +
	"allocation\"N\n" +
	"\x0eReleaseRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\"\x11\n" +
	"\x0fReleaseResponse\";\n" +
	"\x14GetAllocationRequest\x12#\n" +
	"\rsubscriber_id\x18\x01 \x01(\tR\fsubscriberId\"M\n" +
	"\x15GetAllocationResponse\x124\n" +
	"\n" +
	"allocation\x18\x01 \x01(\v2\x14.nexus.v1.AllocationR\n" +
	"allocation\"1\n" +
	"\x16ListAllocationsRequest\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\"g\n" +
	"\x17ListAllocationsResponse\x126\n" +
	"\vallocations\x18\x01 \x03(\v2\x14.nexus.v1.AllocationR\vallocations\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xab\x02\n" +
	"\x11AllocationService\x12A\n" +
	"\bAllocate\x12\x19.nexus.v1.AllocateRequest\x1a\x1a.nexus.v1.AllocateResponse\x12>\n" +
	"\aRelease\x12\x18.nexus.v1.ReleaseRequest\x1a\x19.nexus.v1.ReleaseResponse\x12F\n" +
	"\x03Get\x12\x1e.nexus.v1.GetAllocationRequest\x1a\x1f.nexus.v1.GetAllocationResponse\x12K\n" +
	"\x04List\x12 .nexus.v1.ListAllocationsRequest\x1a!.nexus.v1.ListAllocationsResponseB?Z=github.com/codelaboratoryltd/nexus/api/proto/nexus/v1;nexusv1b\x06proto3"

var (
	file_nexus_v1_allocation_proto_rawDescOnce sync.Once
	file_nexus_v1_allocation_proto_rawDescData []byte
)

func file_nexus_v1_allocation_proto_rawDescGZIP() []byte {
	file_nexus_v1_allocation_proto_rawDescOnce.Do(func() {
		file_nexus_v1_allocation_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v1_allocation_proto_rawDesc), len(file_nexus_v1_allocation_proto_rawDesc)))
	})
	return file_nexus_v1_allocation_proto_rawDescData
}

var file_nexus_v1_allocation_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nexus_v1_allocation_proto_goTypes = []any{
	(*Allocation)(nil),              // 0: nexus.v1.Allocation
	(*AllocateRequest)(nil),         // 1: nexus.v1.AllocateRequest
	(*AllocateResponse)(nil),        // 2: nexus.v1.AllocateResponse
	(*ReleaseRequest)(nil),          // 3: nexus.v1.ReleaseRequest
	(*ReleaseResponse)(nil),         // 4: nexus.v1.ReleaseResponse
	(*GetAllocationRequest)(nil),    // 5: nexus.v1.GetAllocationRequest
	(*GetAllocationResponse)(nil),   // 6: nexus.v1.GetAllocationResponse
	(*ListAllocationsRequest)(nil),  // 7: nexus.v1.ListAllocationsRequest
	(*ListAllocationsResponse)(nil), // 8: nexus.v1.ListAllocationsResponse
	(*timestamppb.Timestamp)(nil),   // 9: google.protobuf.Timestamp
}
var file_nexus_v1_allocation_proto_depIdxs = []int32{
	9,  // 0: nexus.v1.Allocation.timestamp:type_name -> google.protobuf.Timestamp
	9,  // 1: nexus.v1.Allocation.expires_at:type_name -> google.protobuf.Timestamp
	9,  // 2: nexus.v1.Allocation.last_renewed:type_name -> google.protobuf.Timestamp
	0,  // 3: nexus.v1.AllocateResponse.allocation:type_name -> nexus.v1.Allocation
	0,  // 4: nexus.v1.GetAllocationResponse.allocation:type_name -> nexus.v1.Allocation
	0,  // 5: nexus.v1.ListAllocationsResponse.allocations:type_name -> nexus.v1.Allocation
	1,  // 6: nexus.v1.AllocationService.Allocate:input_type -> nexus.v1.AllocateRequest
	3,  // 7: nexus.v1.AllocationService.Release:input_type -> nexus.v1.ReleaseRequest
	5,  // 8: nexus.v1.AllocationService.Get:input_type -> nexus.v1.GetAllocationRequest
	7,  // 9: nexus.v1.AllocationService.List:input_type -> nexus.v1.ListAllocationsRequest
	2,  // 10: nexus.v1.AllocationService.Allocate:output_type -> nexus.v1.AllocateResponse
	4,  // 11: nexus.v1.AllocationService.Release:output_type -> nexus.v1.ReleaseResponse
	6,  // 12: nexus.v1.AllocationService.Get:output_type -> nexus.v1.GetAllocationResponse
	8,  // 13: nexus.v1.AllocationService.List:output_type -> nexus.v1.ListAllocationsResponse
	10, // [10:14] is the sub-list for method output_type
	6,  // [6:10] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_nexus_v1_allocation_proto_init() }
func file_nexus_v1_allocation_proto_init() {
	if File_nexus_v1_allocation_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v1_allocation_proto_rawDesc), len(file_nexus_v1_allocation_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v1_allocation_proto_goTypes,
		DependencyIndexes: file_nexus_v1_allocation_proto_depIdxs,
		MessageInfos:      file_nexus_v1_allocation_proto_msgTypes,
	}.Build()
	File_nexus_v1_allocation_proto = out.File
	file_nexus_v1_allocation_proto_goTypes = nil
	file_nexus_v1_allocation_proto_depIdxs = nil
}
