// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: nexus/v1/node.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Node struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	BestBefore    *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=best_before,json=bestBefore,proto3" json:"best_before,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Node) Reset() {
	*x = Node{}
	mi := &file_nexus_v1_node_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Node) ProtoMessage() {}

func (x *Node) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Node.ProtoReflect.Descriptor instead.
func (*Node) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{0}
}

func (x *Node) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Node) GetBestBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.BestBefore
	}
	return nil
}

func (x *Node) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Node) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type RegisterRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	NodeId   string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Metadata map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// TTL in seconds for the node's best-before time.
	TtlSeconds    int64 `protobuf:"varint,3,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_nexus_v1_node_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RegisterRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RegisterRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type RegisterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_nexus_v1_node_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type HeartbeatRequest struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	NodeId string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	// TTL in seconds to extend the node's best-before time.
	TtlSeconds    int64 `protobuf:"varint,2,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_nexus_v1_node_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{3}
}

func (x *HeartbeatRequest) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *HeartbeatRequest) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Node          *Node                  `protobuf:"bytes,1,opt,name=node,proto3" json:"node,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_nexus_v1_node_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{4}
}

func (x *HeartbeatResponse) GetNode() *Node {
	if x != nil {
		return x.Node
	}
	return nil
}

type ListNodesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesRequest) Reset() {
	*x = ListNodesRequest{}
	mi := &file_nexus_v1_node_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesRequest) ProtoMessage() {}

func (x *ListNodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesRequest.ProtoReflect.Descriptor instead.
func (*ListNodesRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{5}
}

type ListNodesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nodes         []*Node                `protobuf:"bytes,1,rep,name=nodes,proto3" json:"nodes,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNodesResponse) Reset() {
	*x = ListNodesResponse{}
	mi := &file_nexus_v1_node_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNodesResponse) ProtoMessage() {}

func (x *ListNodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_node_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNodesResponse.ProtoReflect.Descriptor instead.
func (*ListNodesResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_node_proto_rawDescGZIP(), []int{6}
}

func (x *ListNodesResponse) GetNodes() []*Node {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *ListNodesResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_nexus_v1_node_proto protoreflect.FileDescriptor

const file_nexus_v1_node_proto_rawDesc = "" +
	"\n" +
	"\x13nexus/v1/node.proto\x12\bnexus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe2\x01\n" +
	"\x04Node\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12;\n" +
	"\vbest_before\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"bestBefore\x128\n" +
	"\bmetadata\x18\x03 \x03(\v2\x1c.nexus.v1.Node.MetadataEntryR\bmetadata\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcd\x01\n" +
	"\x0fRegisterRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12C\n" +
	"\bmetadata\x18\x02 \x03(\v2'.nexus.v1.RegisterRequest.MetadataEntryR\bmetadata\x12\x1f\n" +
	"\vttl_seconds\x18\x03 \x01(\x03R\n" +
	"ttlSeconds\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"6\n" +
	"\x10RegisterResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.nexus.v1.NodeR\x04node\"L\n" +
	"\x10HeartbeatRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x12\x1f\n" +
	"\vttl_seconds\x18\x02 \x01(\x03R\n" +
	"ttlSeconds\"7\n" +
	"\x11HeartbeatResponse\x12\"\n" +
	"\x04node\x18\x01 \x01(\v2\x0e.nexus.v1.NodeR\x04node\"\x12\n" +
	"\x10ListNodesRequest\"O\n" +
	"\x11ListNodesResponse\x12$\n" +
	"\x05nodes\x18\x01 \x03(\v2\x0e.nexus.v1.NodeR\x05nodes\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count2\xdc\x01\n" +
	"\vNodeService\x12A\n" +
	"\bRegister\x12\x19.nexus.v1.RegisterRequest\x1a\x1a.nexus.v1.RegisterResponse\x12D\n" +
	"\tHeartbeat\x12\x1a.nexus.v1.HeartbeatRequest\x1a\x1b.nexus.v1.HeartbeatResponse\x12D\n" +
	"\tListNodes\x12\x1a.nexus.v1.ListNodesRequest\x1a\x1b.nexus.v1.ListNodesResponseB?Z=github.com/codelaboratoryltd/nexus/api/proto/nexus/v1;nexusv1b\x06proto3"

var (
	file_nexus_v1_node_proto_rawDescOnce sync.Once
	file_nexus_v1_node_proto_rawDescData []byte
)

func file_nexus_v1_node_proto_rawDescGZIP() []byte {
	file_nexus_v1_node_proto_rawDescOnce.Do(func() {
		file_nexus_v1_node_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v1_node_proto_rawDesc), len(file_nexus_v1_node_proto_rawDesc)))
	})
	return file_nexus_v1_node_proto_rawDescData
}

var file_nexus_v1_node_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_nexus_v1_node_proto_goTypes = []any{
	(*Node)(nil),                  // 0: nexus.v1.Node
	(*RegisterRequest)(nil),       // 1: nexus.v1.RegisterRequest
	(*RegisterResponse)(nil),      // 2: nexus.v1.RegisterResponse
	(*HeartbeatRequest)(nil),      // 3: nexus.v1.HeartbeatRequest
	(*HeartbeatResponse)(nil),     // 4: nexus.v1.HeartbeatResponse
	(*ListNodesRequest)(nil),      // 5: nexus.v1.ListNodesRequest
	(*ListNodesResponse)(nil),     // 6: nexus.v1.ListNodesResponse
	nil,                           // 7: nexus.v1.Node.MetadataEntry
	nil,                           // 8: nexus.v1.RegisterRequest.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
}
var file_nexus_v1_node_proto_depIdxs = []int32{
	9, // 0: nexus.v1.Node.best_before:type_name -> google.protobuf.Timestamp
	7, // 1: nexus.v1.Node.metadata:type_name -> nexus.v1.Node.MetadataEntry
	8, // 2: nexus.v1.RegisterRequest.metadata:type_name -> nexus.v1.RegisterRequest.MetadataEntry
	0, // 3: nexus.v1.RegisterResponse.node:type_name -> nexus.v1.Node
	0, // 4: nexus.v1.HeartbeatResponse.node:type_name -> nexus.v1.Node
	0, // 5: nexus.v1.ListNodesResponse.nodes:type_name -> nexus.v1.Node
	1, // 6: nexus.v1.NodeService.Register:input_type -> nexus.v1.RegisterRequest
	3, // 7: nexus.v1.NodeService.Heartbeat:input_type -> nexus.v1.HeartbeatRequest
	5, // 8: nexus.v1.NodeService.ListNodes:input_type -> nexus.v1.ListNodesRequest
	2, // 9: nexus.v1.NodeService.Register:output_type -> nexus.v1.RegisterResponse
	4, // 10: nexus.v1.NodeService.Heartbeat:output_type -> nexus.v1.HeartbeatResponse
	6, // 11: nexus.v1.NodeService.ListNodes:output_type -> nexus.v1.ListNodesResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_nexus_v1_node_proto_init() }
func file_nexus_v1_node_proto_init() {
	if File_nexus_v1_node_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v1_node_proto_rawDesc), len(file_nexus_v1_node_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v1_node_proto_goTypes,
		DependencyIndexes: file_nexus_v1_node_proto_depIdxs,
		MessageInfos:      file_nexus_v1_node_proto_msgTypes,
	}.Build()
	File_nexus_v1_node_proto = out.File
	file_nexus_v1_node_proto_goTypes = nil
	file_nexus_v1_node_proto_depIdxs = nil
}
