// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: nexus/v1/pool.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Pool struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cidr           string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Prefix         int32                  `protobuf:"varint,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Exclusions     []string               `protobuf:"bytes,4,rep,name=exclusions,proto3" json:"exclusions,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardingFactor int32                  `protobuf:"varint,6,opt,name=sharding_factor,json=shardingFactor,proto3" json:"sharding_factor,omitempty"`
	BackupRatio    float64                `protobuf:"fixed64,7,opt,name=backup_ratio,json=backupRatio,proto3" json:"backup_ratio,omitempty"`
	Gateway        string                 `protobuf:"bytes,8,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns            []string               `protobuf:"bytes,9,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Pool) Reset() {
	*x = Pool{}
	mi := &file_nexus_v1_pool_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Pool) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pool) ProtoMessage() {}

func (x *Pool) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pool.ProtoReflect.Descriptor instead.
func (*Pool) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{0}
}

func (x *Pool) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Pool) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *Pool) GetPrefix() int32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

func (x *Pool) GetExclusions() []string {
	if x != nil {
		return x.Exclusions
	}
	return nil
}

func (x *Pool) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Pool) GetShardingFactor() int32 {
	if x != nil {
		return x.ShardingFactor
	}
	return 0
}

func (x *Pool) GetBackupRatio() float64 {
	if x != nil {
		return x.BackupRatio
	}
	return 0
}

func (x *Pool) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *Pool) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

type CreatePoolRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cidr           string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	Prefix         int32                  `protobuf:"varint,3,opt,name=prefix,proto3" json:"prefix,omitempty"`
	Exclusions     []string               `protobuf:"bytes,4,rep,name=exclusions,proto3" json:"exclusions,omitempty"`
	Metadata       map[string]string      `protobuf:"bytes,5,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	ShardingFactor int32                  `protobuf:"varint,6,opt,name=sharding_factor,json=shardingFactor,proto3" json:"sharding_factor,omitempty"`
	BackupRatio    float64                `protobuf:"fixed64,7,opt,name=backup_ratio,json=backupRatio,proto3" json:"backup_ratio,omitempty"`
	Gateway        string                 `protobuf:"bytes,8,opt,name=gateway,proto3" json:"gateway,omitempty"`
	Dns            []string               `protobuf:"bytes,9,rep,name=dns,proto3" json:"dns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreatePoolRequest) Reset() {
	*x = CreatePoolRequest{}
	mi := &file_nexus_v1_pool_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolRequest) ProtoMessage() {}

func (x *CreatePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolRequest.ProtoReflect.Descriptor instead.
func (*CreatePoolRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePoolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CreatePoolRequest) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

func (x *CreatePoolRequest) GetPrefix() int32 {
	if x != nil {
		return x.Prefix
	}
	return 0
}

func (x *CreatePoolRequest) GetExclusions() []string {
	if x != nil {
		return x.Exclusions
	}
	return nil
}

func (x *CreatePoolRequest) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *CreatePoolRequest) GetShardingFactor() int32 {
	if x != nil {
		return x.ShardingFactor
	}
	return 0
}

func (x *CreatePoolRequest) GetBackupRatio() float64 {
	if x != nil {
		return x.BackupRatio
	}
	return 0
}

func (x *CreatePoolRequest) GetGateway() string {
	if x != nil {
		return x.Gateway
	}
	return ""
}

func (x *CreatePoolRequest) GetDns() []string {
	if x != nil {
		return x.Dns
	}
	return nil
}

type CreatePoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *Pool                  `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreatePoolResponse) Reset() {
	*x = CreatePoolResponse{}
	mi := &file_nexus_v1_pool_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreatePoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePoolResponse) ProtoMessage() {}

func (x *CreatePoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePoolResponse.ProtoReflect.Descriptor instead.
func (*CreatePoolResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{2}
}

func (x *CreatePoolResponse) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type GetPoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolRequest) Reset() {
	*x = GetPoolRequest{}
	mi := &file_nexus_v1_pool_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolRequest) ProtoMessage() {}

func (x *GetPoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolRequest.ProtoReflect.Descriptor instead.
func (*GetPoolRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{3}
}

func (x *GetPoolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetPoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pool          *Pool                  `protobuf:"bytes,1,opt,name=pool,proto3" json:"pool,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPoolResponse) Reset() {
	*x = GetPoolResponse{}
	mi := &file_nexus_v1_pool_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPoolResponse) ProtoMessage() {}

func (x *GetPoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPoolResponse.ProtoReflect.Descriptor instead.
func (*GetPoolResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{4}
}

func (x *GetPoolResponse) GetPool() *Pool {
	if x != nil {
		return x.Pool
	}
	return nil
}

type ListPoolsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsRequest) Reset() {
	*x = ListPoolsRequest{}
	mi := &file_nexus_v1_pool_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsRequest) ProtoMessage() {}

func (x *ListPoolsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsRequest.ProtoReflect.Descriptor instead.
func (*ListPoolsRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{5}
}

type ListPoolsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Pools         []*Pool                `protobuf:"bytes,1,rep,name=pools,proto3" json:"pools,omitempty"`
	Count         int32                  `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoolsResponse) Reset() {
	*x = ListPoolsResponse{}
	mi := &file_nexus_v1_pool_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoolsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoolsResponse) ProtoMessage() {}

func (x *ListPoolsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoolsResponse.ProtoReflect.Descriptor instead.
func (*ListPoolsResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{6}
}

func (x *ListPoolsResponse) GetPools() []*Pool {
	if x != nil {
		return x.Pools
	}
	return nil
}

func (x *ListPoolsResponse) GetCount() int32 {
	if x != nil {
		return x.Count
	}
	return 0
}

type DeletePoolRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolRequest) Reset() {
	*x = DeletePoolRequest{}
	mi := &file_nexus_v1_pool_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolRequest) ProtoMessage() {}

func (x *DeletePoolRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolRequest.ProtoReflect.Descriptor instead.
func (*DeletePoolRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{7}
}

func (x *DeletePoolRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeletePoolResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeletePoolResponse) Reset() {
	*x = DeletePoolResponse{}
	mi := &file_nexus_v1_pool_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeletePoolResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePoolResponse) ProtoMessage() {}

func (x *DeletePoolResponse) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_pool_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePoolResponse.ProtoReflect.Descriptor instead.
func (*DeletePoolResponse) Descriptor() ([]byte, []int) {
	return file_nexus_v1_pool_proto_rawDescGZIP(), []int{8}
}

var File_nexus_v1_pool_proto protoreflect.FileDescriptor

const file_nexus_v1_pool_proto_rawDesc = "" +
	"\n" +
	"\x13nexus/v1/pool.proto\x12\bnexus.v1\"\xd1\x02\n" +
	"\x04Pool\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\x05R\x06prefix\x12\x1e\n" +
	"\n" +
	"exclusions\x18\x04 \x03(\tR\n" +
	"exclusions\x128\n" +
	"\bmetadata\x18\x05 \x03(\v2\x1c.nexus.v1.Pool.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fsharding_factor\x18\x06 \x01(\x05R\x0eshardingFactor\x12!\n" +
	"\fbackup_ratio\x18\a \x01(\x01R\vbackupRatio\x12\x18\n" +
	"\agateway\x18\b \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\t \x03(\tR\x03dns\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xeb\x02\n" +
	"\x11CreatePoolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\x12\x16\n" +
	"\x06prefix\x18\x03 \x01(\x05R\x06prefix\x12\x1e\n" +
	"\n" +
	"exclusions\x18\x04 \x03(\tR\n" +
	"exclusions\x12E\n" +
	"\bmetadata\x18\x05 \x03(\v2).nexus.v1.CreatePoolRequest.MetadataEntryR\bmetadata\x12'\n" +
	"\x0fsharding_factor\x18\x06 \x01(\x05R\x0eshardingFactor\x12!\n" +
	"\fbackup_ratio\x18\a \x01(\x01R\vbackupRatio\x12\x18\n" +
	"\agateway\x18\b \x01(\tR\agateway\x12\x10\n" +
	"\x03dns\x18\t \x03(\tR\x03dns\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"8\n" +
	"\x12CreatePoolResponse\x12\"\n" +
	"\x04pool\x18\x01 \x01(\v2\x0e.nexus.v1.PoolR\x04pool\" \n" +
	"\x0eGetPoolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"5\n" +
	"\x0fGetPoolResponse\x12\"\n" +
	"\x04pool\x18\x01 \x01(\v2\x0e.nexus.v1.PoolR\x04pool\"\x12\n" +
	"\x10ListPoolsRequest\"O\n" +
	"\x11ListPoolsResponse\x12$\n" +
	"\x05pools\x18\x01 \x03(\v2\x0e.nexus.v1.PoolR\x05pools\x12\x14\n" +
	"\x05count\x18\x02 \x01(\x05R\x05count\"#\n" +
	"\x11DeletePoolRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x14\n" +
	"\x12DeletePoolResponse2\xa5\x02\n" +
	"\vPoolService\x12G\n" +
	"\n" +
	"CreatePool\x12\x1b.nexus.v1.CreatePoolRequest\x1a\x1c.nexus.v1.CreatePoolResponse\x12>\n" +
	"\aGetPool\x12\x18.nexus.v1.GetPoolRequest\x1a\x19.nexus.v1.GetPoolResponse\x12D\n" +
	"\tListPools\x12\x1a.nexus.v1.ListPoolsRequest\x1a\x1b.nexus.v1.ListPoolsResponse\x12G\n" +
	"\n" +
	"DeletePool\x12\x1b.nexus.v1.DeletePoolRequest\x1a\x1c.nexus.v1.DeletePoolResponseB?Z=github.com/codelaboratoryltd/nexus/api/proto/nexus/v1;nexusv1b\x06proto3"

var (
	file_nexus_v1_pool_proto_rawDescOnce sync.Once
	file_nexus_v1_pool_proto_rawDescData []byte
)

func file_nexus_v1_pool_proto_rawDescGZIP() []byte {
	file_nexus_v1_pool_proto_rawDescOnce.Do(func() {
		file_nexus_v1_pool_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v1_pool_proto_rawDesc), len(file_nexus_v1_pool_proto_rawDesc)))
	})
	return file_nexus_v1_pool_proto_rawDescData
}

var file_nexus_v1_pool_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_nexus_v1_pool_proto_goTypes = []any{
	(*Pool)(nil),               // 0: nexus.v1.Pool
	(*CreatePoolRequest)(nil),  // 1: nexus.v1.CreatePoolRequest
	(*CreatePoolResponse)(nil), // 2: nexus.v1.CreatePoolResponse
	(*GetPoolRequest)(nil),     // 3: nexus.v1.GetPoolRequest
	(*GetPoolResponse)(nil),    // 4: nexus.v1.GetPoolResponse
	(*ListPoolsRequest)(nil),   // 5: nexus.v1.ListPoolsRequest
	(*ListPoolsResponse)(nil),  // 6: nexus.v1.ListPoolsResponse
	(*DeletePoolRequest)(nil),  // 7: nexus.v1.DeletePoolRequest
	(*DeletePoolResponse)(nil), // 8: nexus.v1.DeletePoolResponse
	nil,                        // 9: nexus.v1.Pool.MetadataEntry
	nil,                        // 10: nexus.v1.CreatePoolRequest.MetadataEntry
}
var file_nexus_v1_pool_proto_depIdxs = []int32{
	9,  // 0: nexus.v1.Pool.metadata:type_name -> nexus.v1.Pool.MetadataEntry
	10, // 1: nexus.v1.CreatePoolRequest.metadata:type_name -> nexus.v1.CreatePoolRequest.MetadataEntry
	0,  // 2: nexus.v1.CreatePoolResponse.pool:type_name -> nexus.v1.Pool
	0,  // 3: nexus.v1.GetPoolResponse.pool:type_name -> nexus.v1.Pool
	0,  // 4: nexus.v1.ListPoolsResponse.pools:type_name -> nexus.v1.Pool
	1,  // 5: nexus.v1.PoolService.CreatePool:input_type -> nexus.v1.CreatePoolRequest
	3,  // 6: nexus.v1.PoolService.GetPool:input_type -> nexus.v1.GetPoolRequest
	5,  // 7: nexus.v1.PoolService.ListPools:input_type -> nexus.v1.ListPoolsRequest
	7,  // 8: nexus.v1.PoolService.DeletePool:input_type -> nexus.v1.DeletePoolRequest
	2,  // 9: nexus.v1.PoolService.CreatePool:output_type -> nexus.v1.CreatePoolResponse
	4,  // 10: nexus.v1.PoolService.GetPool:output_type -> nexus.v1.GetPoolResponse
	6,  // 11: nexus.v1.PoolService.ListPools:output_type -> nexus.v1.ListPoolsResponse
	8,  // 12: nexus.v1.PoolService.DeletePool:output_type -> nexus.v1.DeletePoolResponse
	9,  // [9:13] is the sub-list for method output_type
	5,  // [5:9] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_nexus_v1_pool_proto_init() }
func file_nexus_v1_pool_proto_init() {
	if File_nexus_v1_pool_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v1_pool_proto_rawDesc), len(file_nexus_v1_pool_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v1_pool_proto_goTypes,
		DependencyIndexes: file_nexus_v1_pool_proto_depIdxs,
		MessageInfos:      file_nexus_v1_pool_proto_msgTypes,
	}.Build()
	File_nexus_v1_pool_proto = out.File
	file_nexus_v1_pool_proto_goTypes = nil
	file_nexus_v1_pool_proto_depIdxs = nil
}
