// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.33.2
// source: nexus/v1/watch.proto

package nexusv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EventType int32

const (
	EventType_EVENT_TYPE_UNSPECIFIED         EventType = 0
	EventType_EVENT_TYPE_POOL_CREATED        EventType = 1
	EventType_EVENT_TYPE_POOL_DELETED        EventType = 2
	EventType_EVENT_TYPE_ALLOCATION_CREATED  EventType = 3
	EventType_EVENT_TYPE_ALLOCATION_RELEASED EventType = 4
	EventType_EVENT_TYPE_NODE_REGISTERED     EventType = 5
	EventType_EVENT_TYPE_NODE_EXPIRED        EventType = 6
)

// Enum value maps for EventType.
var (
	EventType_name = map[int32]string{
		0: "EVENT_TYPE_UNSPECIFIED",
		1: "EVENT_TYPE_POOL_CREATED",
		2: "EVENT_TYPE_POOL_DELETED",
		3: "EVENT_TYPE_ALLOCATION_CREATED",
		4: "EVENT_TYPE_ALLOCATION_RELEASED",
		5: "EVENT_TYPE_NODE_REGISTERED",
		6: "EVENT_TYPE_NODE_EXPIRED",
	}
	EventType_value = map[string]int32{
		"EVENT_TYPE_UNSPECIFIED":         0,
		"EVENT_TYPE_POOL_CREATED":        1,
		"EVENT_TYPE_POOL_DELETED":        2,
		"EVENT_TYPE_ALLOCATION_CREATED":  3,
		"EVENT_TYPE_ALLOCATION_RELEASED": 4,
		"EVENT_TYPE_NODE_REGISTERED":     5,
		"EVENT_TYPE_NODE_EXPIRED":        6,
	}
)

func (x EventType) Enum() *EventType {
	p := new(EventType)
	*p = x
	return p
}

func (x EventType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EventType) Descriptor() protoreflect.EnumDescriptor {
	return file_nexus_v1_watch_proto_enumTypes[0].Descriptor()
}

func (EventType) Type() protoreflect.EnumType {
	return &file_nexus_v1_watch_proto_enumTypes[0]
}

func (x EventType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EventType.Descriptor instead.
func (EventType) EnumDescriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{0}
}

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Filter events by resource type. Empty means all types.
	ResourceTypes []string `protobuf:"bytes,1,rep,name=resource_types,json=resourceTypes,proto3" json:"resource_types,omitempty"`
	// Filter events by pool ID. Empty means all pools.
	PoolId        string `protobuf:"bytes,2,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_nexus_v1_watch_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_watch_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetResourceTypes() []string {
	if x != nil {
		return x.ResourceTypes
	}
	return nil
}

func (x *WatchRequest) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

type WatchEvent struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Type      EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=nexus.v1.EventType" json:"type,omitempty"`
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// The resource ID affected (pool ID, subscriber ID, or node ID).
	ResourceId string `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	// Optional payload depending on event type.
	//
	// Types that are valid to be assigned to Payload:
	//
	//	*WatchEvent_Pool
	//	*WatchEvent_Allocation
	//	*WatchEvent_Node
	Payload       isWatchEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchEvent) Reset() {
	*x = WatchEvent{}
	mi := &file_nexus_v1_watch_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchEvent) ProtoMessage() {}

func (x *WatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_watch_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchEvent.ProtoReflect.Descriptor instead.
func (*WatchEvent) Descriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{1}
}

func (x *WatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *WatchEvent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *WatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

func (x *WatchEvent) GetPayload() isWatchEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WatchEvent) GetPool() *PoolEvent {
	if x != nil {
		if x, ok := x.Payload.(*WatchEvent_Pool); ok {
			return x.Pool
		}
	}
	return nil
}

func (x *WatchEvent) GetAllocation() *AllocationEvent {
	if x != nil {
		if x, ok := x.Payload.(*WatchEvent_Allocation); ok {
			return x.Allocation
		}
	}
	return nil
}

func (x *WatchEvent) GetNode() *NodeEvent {
	if x != nil {
		if x, ok := x.Payload.(*WatchEvent_Node); ok {
			return x.Node
		}
	}
	return nil
}

type isWatchEvent_Payload interface {
	isWatchEvent_Payload()
}

type WatchEvent_Pool struct {
	Pool *PoolEvent `protobuf:"bytes,4,opt,name=pool,proto3,oneof"`
}

type WatchEvent_Allocation struct {
	Allocation *AllocationEvent `protobuf:"bytes,5,opt,name=allocation,proto3,oneof"`
}

type WatchEvent_Node struct {
	Node *NodeEvent `protobuf:"bytes,6,opt,name=node,proto3,oneof"`
}

func (*WatchEvent_Pool) isWatchEvent_Payload() {}

func (*WatchEvent_Allocation) isWatchEvent_Payload() {}

func (*WatchEvent_Node) isWatchEvent_Payload() {}

type PoolEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Cidr          string                 `protobuf:"bytes,2,opt,name=cidr,proto3" json:"cidr,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PoolEvent) Reset() {
	*x = PoolEvent{}
	mi := &file_nexus_v1_watch_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PoolEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PoolEvent) ProtoMessage() {}

func (x *PoolEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_watch_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PoolEvent.ProtoReflect.Descriptor instead.
func (*PoolEvent) Descriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{2}
}

func (x *PoolEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PoolEvent) GetCidr() string {
	if x != nil {
		return x.Cidr
	}
	return ""
}

type AllocationEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PoolId        string                 `protobuf:"bytes,1,opt,name=pool_id,json=poolId,proto3" json:"pool_id,omitempty"`
	SubscriberId  string                 `protobuf:"bytes,2,opt,name=subscriber_id,json=subscriberId,proto3" json:"subscriber_id,omitempty"`
	Ip            string                 `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	NodeId        string                 `protobuf:"bytes,4,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AllocationEvent) Reset() {
	*x = AllocationEvent{}
	mi := &file_nexus_v1_watch_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AllocationEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AllocationEvent) ProtoMessage() {}

func (x *AllocationEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_watch_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AllocationEvent.ProtoReflect.Descriptor instead.
func (*AllocationEvent) Descriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{3}
}

func (x *AllocationEvent) GetPoolId() string {
	if x != nil {
		return x.PoolId
	}
	return ""
}

func (x *AllocationEvent) GetSubscriberId() string {
	if x != nil {
		return x.SubscriberId
	}
	return ""
}

func (x *AllocationEvent) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *AllocationEvent) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type NodeEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Metadata      map[string]string      `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeEvent) Reset() {
	*x = NodeEvent{}
	mi := &file_nexus_v1_watch_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeEvent) ProtoMessage() {}

func (x *NodeEvent) ProtoReflect() protoreflect.Message {
	mi := &file_nexus_v1_watch_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeEvent.ProtoReflect.Descriptor instead.
func (*NodeEvent) Descriptor() ([]byte, []int) {
	return file_nexus_v1_watch_proto_rawDescGZIP(), []int{4}
}

func (x *NodeEvent) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *NodeEvent) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_nexus_v1_watch_proto protoreflect.FileDescriptor

const file_nexus_v1_watch_proto_rawDesc = "" +
	"\n" +
	"\x14nexus/v1/watch.proto\x12\bnexus.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"N\n" +
	"\fWatchRequest\x12%\n" +
	"\x0eresource_types\x18\x01 \x03(\tR\rresourceTypes\x12\x17\n" +
	"\apool_id\x18\x02 \x01(\tR\x06poolId\"\xae\x02\n" +
	"\n" +
	"WatchEvent\x12'\n" +
	"\x04type\x18\x01 \x01(\x0e2\x13.nexus.v1.EventTypeR\x04type\x128\n" +
	"\ttimestamp\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\x12)\n" +
	"\x04pool\x18\x04 \x01(\v2\x13.nexus.v1.PoolEventH\x00R\x04pool\x12;\n" +
	"\n" +
	"allocation\x18\x05 \x01(\v2\x19.nexus.v1.AllocationEventH\x00R\n" +
	"allocation\x12)\n" +
	"\x04node\x18\x06 \x01(\v2\x13.nexus.v1.NodeEventH\x00R\x04nodeB\t\n" +
	"\apayload\"/\n" +
	"\tPoolEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04cidr\x18\x02 \x01(\tR\x04cidr\"x\n" +
	"\x0fAllocationEvent\x12\x17\n" +
	"\apool_id\x18\x01 \x01(\tR\x06poolId\x12#\n" +
	"\rsubscriber_id\x18\x02 \x01(\tR\fsubscriberId\x12\x0e\n" +
	"\x02ip\x18\x03 \x01(\tR\x02ip\x12\x17\n" +
	"\anode_id\x18\x04 \x01(\tR\x06nodeId\"\x97\x01\n" +
	"\tNodeEvent\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12=\n" +
	"\bmetadata\x18\x02 \x03(\v2!.nexus.v1.NodeEvent.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\xe5\x01\n" +
	"\tEventType\x12\x1a\n" +
	"\x16EVENT_TYPE_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17EVENT_TYPE_POOL_CREATED\x10\x01\x12\x1b\n" +
	"\x17EVENT_TYPE_POOL_DELETED\x10\x02\x12!\n" +
	"\x1dEVENT_TYPE_ALLOCATION_CREATED\x10\x03\x12\"\n" +
	"\x1eEVENT_TYPE_ALLOCATION_RELEASED\x10\x04\x12\x1e\n" +
	"\x1aEVENT_TYPE_NODE_REGISTERED\x10\x05\x12\x1b\n" +
	"\x17EVENT_TYPE_NODE_EXPIRED\x10\x062G\n" +
	"\fWatchService\x127\n" +
	"\x05Watch\x12\x16.nexus.v1.WatchRequest\x1a\x14.nexus.v1.WatchEvent0\x01B?Z=github.com/codelaboratoryltd/nexus/api/proto/nexus/v1;nexusv1b\x06proto3"

var (
	file_nexus_v1_watch_proto_rawDescOnce sync.Once
	file_nexus_v1_watch_proto_rawDescData []byte
)

func file_nexus_v1_watch_proto_rawDescGZIP() []byte {
	file_nexus_v1_watch_proto_rawDescOnce.Do(func() {
		file_nexus_v1_watch_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_nexus_v1_watch_proto_rawDesc), len(file_nexus_v1_watch_proto_rawDesc)))
	})
	return file_nexus_v1_watch_proto_rawDescData
}

var file_nexus_v1_watch_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_nexus_v1_watch_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_nexus_v1_watch_proto_goTypes = []any{
	(EventType)(0),                // 0: nexus.v1.EventType
	(*WatchRequest)(nil),          // 1: nexus.v1.WatchRequest
	(*WatchEvent)(nil),            // 2: nexus.v1.WatchEvent
	(*PoolEvent)(nil),             // 3: nexus.v1.PoolEvent
	(*AllocationEvent)(nil),       // 4: nexus.v1.AllocationEvent
	(*NodeEvent)(nil),             // 5: nexus.v1.NodeEvent
	nil,                           // 6: nexus.v1.NodeEvent.MetadataEntry
	(*timestamppb.Timestamp)(nil), // 7: google.protobuf.Timestamp
}
var file_nexus_v1_watch_proto_depIdxs = []int32{
	0, // 0: nexus.v1.WatchEvent.type:type_name -> nexus.v1.EventType
	7, // 1: nexus.v1.WatchEvent.timestamp:type_name -> google.protobuf.Timestamp
	3, // 2: nexus.v1.WatchEvent.pool:type_name -> nexus.v1.PoolEvent
	4, // 3: nexus.v1.WatchEvent.allocation:type_name -> nexus.v1.AllocationEvent
	5, // 4: nexus.v1.WatchEvent.node:type_name -> nexus.v1.NodeEvent
	6, // 5: nexus.v1.NodeEvent.metadata:type_name -> nexus.v1.NodeEvent.MetadataEntry
	1, // 6: nexus.v1.WatchService.Watch:input_type -> nexus.v1.WatchRequest
	2, // 7: nexus.v1.WatchService.Watch:output_type -> nexus.v1.WatchEvent
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_nexus_v1_watch_proto_init() }
func file_nexus_v1_watch_proto_init() {
	if File_nexus_v1_watch_proto != nil {
		return
	}
	file_nexus_v1_watch_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchEvent_Pool)(nil),
		(*WatchEvent_Allocation)(nil),
		(*WatchEvent_Node)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_nexus_v1_watch_proto_rawDesc), len(file_nexus_v1_watch_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_nexus_v1_watch_proto_goTypes,
		DependencyIndexes: file_nexus_v1_watch_proto_depIdxs,
		EnumInfos:         file_nexus_v1_watch_proto_enumTypes,
		MessageInfos:      file_nexus_v1_watch_proto_msgTypes,
	}.Build()
	File_nexus_v1_watch_proto = out.File
	file_nexus_v1_watch_proto_goTypes = nil
	file_nexus_v1_watch_proto_depIdxs = nil
}
